# Generated by Django 2.1 on 2022-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payway',
            name='time',
            field=models.IntegerField(),
        ),
    ]
