# Generated by Django 2.1 on 2022-02-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220204_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payway',
            name='time',
            field=models.IntegerField(blank=0),
        ),
    ]
