# Generated by Django 2.1 on 2022-02-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220204_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coz_name', models.TextField(max_length=10)),
                ('coz_price', models.TextField(max_length=10)),
                ('issue_date', models.TimeField(blank=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.FloatField(max_length=20)),
                ('discount_price', models.FloatField(max_length=20)),
                ('total', models.FloatField(blank=1)),
            ],
        ),
    ]
